
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#? ??? DB? ?? ?? ????. ?? ?? ????, example ??? database ???? ??, ????,????? ???? ????.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/example?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
  kakao:
    rest_api_key: 15c42d10e537f8f950496465e2edc8c0
    admin_key: 7f1ed1e02916c6bb166699a10a0992c8
    client_secret: 513408R76Akp4SE3TuqsroTBZ2nPcME9
    redirect_token_uri: https://kauth.kakao.com/oauth/token
    my_info_uri: https://kapi.kakao.com/v2/user/me

