version: '3'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 3300:8080 
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    ports:
      - "8000:8080"
    privileged: true
    user: root
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
